name: Automated API tests using Postman CLI

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "18247444-4c4a9418-642c-4208-b2c3-2bd53d0ed793"
